### ISSUE TITLE
CrashLoopBackOff after deploying photoalbum-app to GKE

### ISSUE THREAD

**Issue by FelipeLujan** [GoogleCloudPlatform/gke-photoalbum-example#2]
Hi. 

I'm trying to complete this tutorial in GCP after deploying the containerized photoalbum-app,  i'm getting CrashLoopBackOff  on all 3 of the pods running photoalbum-app.
I tried changing the password and username with the ones set up on [this step](https://cloud.google.com/solutions/integrating-microservices-with-pubsub#creating_a_cloud_sql_instance_and_a_mysql_database) and leaving  USERNAME = 'username' PASSWORD = 'passw0rd' but i can't make the photoapp deploy succeed. 
thumbnail-worker is working fine tho.

Could you guys please help me out

**Comment by hasebe** [comment]
@FelipeLujan Sorry to keep you waiting so long.
Could you solve the issue? If not, would you please share logs and exit code of pods for photoalbum-app?
You can find how to get them [here](https://cloud.google.com/kubernetes-engine/docs/troubleshooting#CrashLoopBackOff)

**Comment by enakai00** [comment]
We've updated codes and confirmed that it works as intended.
