### ISSUE TITLE
Yaml files need to be updated

### ISSUE THREAD

**Issue by brightlee6** [GoogleCloudPlatform/gke-photoalbum-example#4]
I think these yaml files need to be updated with new kubectl version.

When I ran this:
kubectl create -f config/photoalbum-deployment.yaml
error: unable to recognize "config/photoalbum-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

Re-run after changing to apps/v1
error: error validating "config/photoalbum-deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

Re-run with –validate=false
The Deployment "photoalbum-app" is invalid: 
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"name":"photoalbum-app"}: `selector` does not match template `labels`

Here is my kubectl version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

Thanks.

**Comment by enakai00** [comment]
Thanks for reporting the issue. We've updated the config files.
